# Generated by Django 5.2.4 on 2025-07-28 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('named_url', models.CharField(blank=True, max_length=100, verbose_name='Имя ссылки')),
                ('menu_name', models.CharField(max_length=50, verbose_name='Название меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem')),
            ],
        ),
    ]
